services:
  web:
    build: .
    image: message-app
    container_name: message_app_web
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - message_app_network
    environment:
      - FLASK_ENV=development

networks:
  message_app_network:
    external: true